/**
 * payload_shape.mjs — offline evidence: what would Pi actually send to the
 * Google API for an audio attachment? (issue #30)
 *
 * This runs Pi's OWN Google provider converter (`pi-ai dist/api/google-shared.js
 * convertMessages`) over synthetic transcripts, so the printed request shape is
 * produced by Pi's code, not reimplemented here. No network, no credentials.
 *
 * Cases:
 *   user   — user message with a text block + an audio-typed content block
 *            (the audio bridge's injection shape),
 *   tool   — tool result with an audio-typed content block
 *            (what a tool-returning-image shape would produce).
 *
 * Output is sanitized by default: base64 payloads are replaced by a redaction
 * marker with length + sha256. Use --show-data to print raw base64 (never do
 * this into reports).
 *
 * Usage: node probe/payload_shape.mjs [--show-data] [--json]
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { piUrls } from "./pi_install.mjs";

const showData = process.argv.includes("--show-data");
const asJson = process.argv.includes("--json");

const urls = piUrls();
if (!urls) {
  console.error("Pi installation not found. Set PI_INSTALL_DIR to the @earendil-works/pi-coding-agent directory.");
  process.exit(2);
}

const { convertMessages } = await import(urls.piAiApi("google-shared.js"));
const catalog = JSON.parse(readFileSync(urls.googleCatalog, "utf-8"));
const model = catalog["google-generative-ai"]["gemini-3.8-flash"];
if (!model) {
  console.error("gemini-3.8-flash not found in the installed Google catalog");
  process.exit(2);
}

// Minimal WAV-ish bytes are enough: convertMessages passes bytes through
// untouched. (Real fixtures are generated by probe/make_fixture.py.)
// The payload is deliberately > 64 base64 chars so the redaction path is
// exercised even in this synthetic case.
const audioBytes = Buffer.concat([Buffer.from("RIFF\0\0\0\0WAVEfmt "), Buffer.alloc(512)]);
const audioB64 = audioBytes.toString("base64");
const AUDIO_MIME = "audio/wav";

function sanitize(part) {
  const clone = JSON.parse(JSON.stringify(part));
  const walk = (node) => {
    if (Array.isArray(node)) return node.forEach(walk);
    if (node && typeof node === "object") {
      for (const key of Object.keys(node)) {
        if (key === "data" && typeof node[key] === "string" && node[key].length > 64) {
          node[key] = showData
            ? node[key]
            : `<base64 redacted: ${node[key].length} chars, sha256 ${createHash("sha256")
                .update(node[key])
                .digest("hex")
                .slice(0, 16)}…>`;
        } else {
          walk(node[key]);
        }
      }
    }
  };
  walk(clone);
  return clone;
}

const cases = {
  user: {
    description: "user message: text block + audio content block (audio bridge injection shape)",
    context: {
      messages: [
        {
          role: "user",
          timestamp: 0,
          content: [
            { type: "text", text: "What do you hear?" },
            { type: "image", mimeType: AUDIO_MIME, data: audioB64 },
          ],
        },
      ],
    },
  },
  tool: {
    description: "tool result: audio content block (Gemini>=3 nests tool images into functionResponse.parts)",
    context: {
      messages: [
        { role: "user", timestamp: 0, content: "listen to it" },
        {
          role: "assistant",
          timestamp: 1,
          api: "google-generative-ai",
          provider: "google",
          model: "gemini-3.8-flash",
          usage: { input: 1, output: 1, cacheRead: 0, cacheWrite: 0, totalTokens: 2, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } },
          stopReason: "toolUse",
          content: [{ type: "toolCall", id: "t1", name: "audio_attach", arguments: {} }],
        },
        {
          role: "toolResult",
          toolCallId: "t1",
          toolName: "audio_attach",
          isError: false,
          timestamp: 2,
          content: [{ type: "image", mimeType: AUDIO_MIME, data: audioB64 }],
        },
      ],
    },
  },
};

const out = {};
for (const [name, testCase] of Object.entries(cases)) {
  const contents = convertMessages(model, testCase.context);
  out[name] = {
    description: testCase.description,
    requestContents: contents.map(sanitize),
  };
}

const payloadSummary = {
  model: { id: model.id, provider: model.provider, api: model.api, input: model.input },
  note:
    "inlineData carries MIME + raw bytes (no file URI, no Gemini Files API upload). " +
    "Pi's message types have no audio block; the block is typed 'image' with an audio MIME by the bridge.",
  cases: out,
};

if (asJson) {
  console.log(JSON.stringify(payloadSummary, null, 2));
} else {
  console.log(`Pi package        : ${urls.dir}`);
  console.log(`model             : ${model.provider}/${model.id} (api=${model.api}, input=${JSON.stringify(model.input)})`);
  for (const [name, value] of Object.entries(out)) {
    console.log(`\n--- case: ${name} ---`);
    console.log(value.description);
    console.log(JSON.stringify(value.requestContents, null, 2));
  }
}
